### ISSUE TITLE
ropm init might like to help set the root folder

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/ropm#1]
when doing ropm init; it'd be nice if
1: if package.json exists, offer to add the root folder property
2. if it doesn't do the npm init, then offer to add the root folder property

this is coz many projects have sources (and therefore ropm root folders) located in src/ template/ some-other-folder/

**Comment by TwitchBronBron** [comment]
This has been added starting in [v0.6.4](https://github.com/rokucommunity/ropm/blob/master/CHANGELOG.md#064)
