### ISSUE TITLE
how to deal with transitive dependencies?

### ISSUE THREAD

**Issue by ZeeD** [rokucommunity/ropm#55]
I'm trying to write a (bs) library, that itself relies on some libraries that I found - like, for example (rodash)[https://github.com/TKSS-Software/rodash], and (roku-log)[https://github.com/georgejecook/roku-log].

I started using `ropm`, and it was easy to "consume" the other libraries. For how I understood, it creates a subfolder for each dependency in `/source/roku_modules` and/or `/component/roku_modules`, so they are "part of the project".

Now I have doubts trying to create a package to publish myself (unfortunately it will be private, but still)

* when I create a package, it seems that the dependencies are bundled inside, witch is something I don't expect. Is this correct?
* It's not clear to me how transitive dependencies work? Let's say that I have an "application" A, that depends on rodash, and on my library L, that itself depends on rodash. 

```mermaid
flowchart
    A --> rodash
    A --> lib
    lib --> rodash
```

what happens in A? does it have two "copies" of rodash?

**Comment by TwitchBronBron** [comment]
You should explicitly exclude the roku_modules folders when publishing your package to npm. ropm will handle installing the dependencies in the proper locations, rewriting import paths ,etc. We briefly talk about this in the readme. 

https://github.com/rokucommunity/ropm#changing-where-the-modules-files-are-copied-from-as-a-package-author
> All folders named roku_modules that are found in a ropm module will be ignored. This is due to the fact that modules should not be publishing their own copies of their ropm modules. ropm will handle this for them. So as a package author, be sure to exclude all folders named roku_modules during your publishing process.

ropm will read the `dependencies` section of your project and all transitive dependencies, and narrow the versions of the library. See [this readme section](https://github.com/rokucommunity/ropm#version-narrowing).

**Comment by ZeeD** [comment]
just to be sure: in the final .tgz there should be the compiled files, correct? (I expect to find `.brs` and maybe `.d.bs` with the definitions) so I need to use `bsc` to compile my project (I saw other projects use `npx bsc --create-package false --staging-folder-path staging` to basically create a folder with `.brs` files). But then I cannot blacklist the roku modules (as they are needed at this stage)

maybe I'm dense, but I don't get what is the "command" to create / publish a package. If it is `npm` (as in `npm pack`/`npm publish`) how does it know that he should ignore the roku_modules? it doesn't seams to me that `ropm` is able to do it, and `bsc` creates `.zip` files (that are meant to be "deployed" on roku devices, not on a `npm` registry)

**Comment by TwitchBronBron** [comment]
Here's the steps to publish a ropm package with bsc and the `npm` cli. 
1. Set `"retainStagingFolder": true` and `"stagingFolderPath": "dist"` in your `bsconfig.json`. (`dist` is just my favorite output directory name, but you can call it whatever you want). 
2. Run `bsc`, so now the the `dist` folder will contain all of the transpiled files.
3. In your library project's `package.json`, set the `"files"` array to something like this:
    ```
    {
        "name": "quick-list"
        //when npm creates the package, only include these files
        "files": [
            "dist/**/*",
            
        ],
        "ropm": {
            //tell ropm that the files for this module reside in the "./dist" folder
            "packageRootDir": "dist",
            //exclude all roku_modules files when creating npm package. 
            "!**/roku_modules/**/*"
        }
    }
    ```
4. follow the standard npm docs for how to publish an npm package. See [this section](https://github.com/rokucommunity/ropm#how-to-create-a-ropm-package) in the readme for instructions.

**Comment by ZeeD** [comment]
Thanks! I think I got now.
To better understand what was happening I created a (very dumb) example on https://github.com/ZeeD/_bs_lib_monorepo where I tried to follow your advices
